version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - 8000:8000
    networks:
      equinox:
    depends_on:
      - backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - 8080:8080
    networks:
      equinox:

networks:
  equinox:
